# Dependabot configuration for automatic dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'UTC'
    # Group all minor and patch updates together
    groups:
      dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    # Keep pull requests up to date with rebasing
    rebase-strategy: 'auto'
    # Limit the number of open pull requests
    open-pull-requests-limit: 5
    # Add labels to pull requests
    labels:
      - 'dependencies'
      - 'automated'
    # Commit message prefix
    commit-message:
      prefix: 'chore'
      include: 'scope'
